### PR TITLE
Series of fixes and updates for orbit interpolations in NEST

### PR DESCRIPTION
**Pull request by pmar**
The orbit interpolations in NEST (and BEAM) were _completely_ broken. ApplyOrbitOp would introduce errors in range of 0.5 - 1.5 meters in X, Y, Z directions. Velocities were also effected. These errors would scale with the size of the frame, and wrt the distance between seed and interpolation points. 
The orbit interpolation errors would show up, in both the interferometric (eg, the flat earth phase would not be correctly removed), and SAR applications (eg, errors in terrain correction, etc). In general any operation building on geometry/orbits was effected by this problem.

This pull request fixes all the observed issues!

Also the numerical comparison between: 'getorb' package, internally developed Matlab tools, and patched NEST orbit interpolators was performed. With this pull request, the difference between NEST and other orbit interpolators is on few mm's level (1-3mm depending on the axis). This very small difference can be attributed to: (1) the orbit noise, (2) to the numerical precision (getorb works with floats, and orbits are annotated with mm precision), and (3) slightly different GRS80 parameters used in Getorb and NEST. Anyhow, these difference we can consider as system noise, and ignore.

For more details and specific code changes see commit log. 

Notes and remarks:
- Checks and orbit correction for the 'leap second' are implemented; but still not pushed to public branches because of lack of testing. With this changes I believe we should resolve for the issue reported here: https://earth.esa.int/web/guest/-/leap-second-impact-on-envisat-data-on-1-january-2009-6032
- BEAM is also affected by this problem - EnvisatOrbitReader() class. I'll issue a separate pull request to merge in this fixes into BEAM.

### CODE REVIEW

**Comment by pmar** [comment]
Clarification about commit messages: 

Perhaps it is a bit confusing that this pull request contains parts of jLinda's log history - this should not happen with git submodules. However, I didn't set-up IntelliJ correctly, actually it somehow defaulted to "Synchronous branch control", and changes from jLinda propagated into NEST history. 

Still jLinda commits are just references to the subproject commits. And since anyhow NEST would have to be updated to point to new jLinda's HEAD, I decided not to spend much time cleaning up the log history of NEST, and to leave it like it is.

Sorry about this _dirt_ in the log history.

**Comment by lveci** [comment]
Petar, for this reason, I've merged from the command line rather than the
github pull request to be safe.

Will there be more updates today? When do you plan to merge the branches?

**Comment by pmar** [comment]
I think it should be fine to integrate this via the pull request. I just tried pull request merge on some temp branch, and except for noise in the history there are no other problems.

You actually also need those jLinda commits, since they point where to attach/detach HEAD in jLinda for the integration with NEST.

Anyhow, please push your changes, so that I can pull and push the rest of my stuff.

**Comment by pmar** [comment]
Note: I just pushed update for the ApplyOrbitOp help operator. This one should be coordinated with Andrea perhaps.

**Pull request closed without merging**
