### PR TITLE
Update of plugin versions.

### PR DESCRIPTION
**Pull request by pmar**
Update of plugin versions in central pom of NEST.

Notes:
- versions of assembly and compiler plugin would brake the build process, and cause problems in packaging with the latest maven 3.1.1 and jdk 1.7.0_45.
- tested compiling and assembling with this pom on linux64 and win64.
- other plugin versions I do not think are critical, still I updated their versions.

### CODE REVIEW

**Comment by pmar** [comment]
Thanks.

FYI: Also, [Maven IDEA Plugin](http://maven.apache.org/plugins/maven-idea-plugin/) fails to execute correctly with Maven version 3.1.1 - the error below is triggered. With older versions Maven < 3.1.0, the plugin executes correctly. 

I tested this only on linux, so it could be that the issue is platform dependent. Are you seeing this on Windows?

``` bash
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-idea-plugin:2.2.1:idea (default-cli) on project beam-system: Execution default-cli of goal org.apache.maven.plugins:maven-idea-plugin:2.2.1:idea failed. NullPointerException -> [Help 1]
```

Also, considering that the IDEA plugin is being [retired](http://maven.40175.n5.nabble.com/VOTE-Release-Apache-Maven-IDEA-Plugin-version-2-2-1-td5764701.html) it is very unlikely that this would be ever resolved. Any alternatives?

In any case, I import the project into IntelliJ by opening the pom file directly, and would use the mvn plugin as a last resort when IntelliJ would go crazy and not be able to figure out maven configuration correctly. (_Perhaps update the documentation for building from source?_)

``` bash
$ mvn --version
Apache Maven 3.1.1 (0728685237757ffbf44136acec0402957f723d9a; 2013-09-17 17:22:22+0200)
Maven home: /opt/apache/maven/apache-maven-3.1.1
Java version: 1.7.0_45, vendor: Oracle Corporation
Java home: /opt/java/jdk1.7.0_45/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "3.12.5-1-arch", arch: "amd64", family: "unix"
```

**Comment by pmar** [comment]
**Update**: the idea plugin issue seems to be 'environment' related. 

The idea plugin (mvn compile idea:idea) runs fine on Windows, but it fails on Linux and Cygwin - very likely something inconsistent on Unix-like environments.

**Comment by lveci** [comment]
I've been running without it for a while now. The built in .idea import is
better than the maven plugin. It just needs a little getting used to.

I'll remove the plugin.

You will need to do a maven import from idea creating a .idea folder. In
idea you'll have a right hand side panel where you can call maven goals.
Create a configuration for a maven compile. The first time, you will still
need to do a maven compile before idea compile because of the resource
files which get copied to output (I'll look into a separating this to
avoid a full compile).

**Comment by pmar** [comment]
Thanks. It seems like no-one is using maven's idea plugin anymore. Also eclipse plugin seem to be poorly maintained. When/if removing it, do not forget beam/pom.xml.

Btw, for me simply opening the project with the central pom would create .idea directory and setup up all maven goals. Only thing, I would do after opening the project like this is to group the goals, and to indeed run compile because of the resource files. I guess it does not really matter whether you compile outside or within idea. Would be great if the full compile can be avoided, although it is the minor thing.

**Pull request merged**
